dist: bionic
language: ruby
rvm: 2.7
before_install:
  - export VOWPALWABBIT_VERSION=8.8.1
  - ./test/ci/install_vowpalwabbit.sh
  - export LD_LIBRARY_PATH=$HOME/vowpalwabbit/$VOWPALWABBIT_VERSION/build/vowpalwabbit:$LD_LIBRARY_PATH
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libboost-math-dev
    - libboost-test-dev
cache:
  bundler: true
  directories:
    - $HOME/vowpalwabbit
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
