environment:
  matrix:
    - RUBY_VERSION: "25-x64"

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd C:\projects\vowpalwabbit
  - git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git
  - cd vowpal_wabbit\vowpalwabbit
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
  - .\vowpal_wabbit.sln
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\projects\vowpalwabbit\vowpal_wabbit\build\vowpalwabbit;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
