image: Visual Studio 2019

environment:
  matrix:
    - RUBY_VERSION: "26-x64"

install:
  - git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git
  - cd vowpal_wabbit/vowpalwabbit
  - msbuild /p:Configuration="Release" /p:Platform="x64" vw.sln
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\projects\vowpalwabbit\vowpal_wabbit\vowpalwabbit\out\target\Release\x64;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test
